"""
This type stub file was generated by pyright.
"""

from typing import Any
from .types import Decorator

def docs_from(obj: Any) -> Decorator:
  """Use the docs from `obj` to decorate `func()`."""
  ...

