"""
This type stub file was generated by pyright.
"""

from os import PathLike
from pathlib import Path
from typing import Callable, Literal

Method[**P,T] = Callable[P, T]
Decoratable[**P,T] = Callable[P, T]
Decorated[**P,T] = Callable[P, T]
Decorator = Callable[[Decoratable], Decorated]
FileMode = TextMode | BinaryMode
TextMode = Literal['r', 'w', 'a', 'x', 'r+', 'w+', 'a+', 'x+']
BinaryMode = Literal['rb', 'wb', 'ab', 'xb', 'r+b', 'w+b', 'a+b', 'x+b']
Paths = Path | PathLike | AsyncPath | AsyncPurePath | str
