services:
  houdini:
    build:
      context: ./houdini-20.5
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        HOUDINI_VERSION: 20.5.584
        HOUDINI_ARCH: arm64
        HOUDINI_BUILD_TYPE: gcc9.3
        BUILDKIT_INLINE_CACHE: 1
      secrets:
        - sidefx_credentials
      target: final
    volumes:
      - ..:/app
      - pip-cache:/root/.cache/pip
      - apt-cache:/var/cache/apt
      - apt-lib:/var/lib/apt
    ports:
      - "5678:5678"

  zabob-mcp:
    build:
      context: ..
      dockerfile: docker/zabob-mcp/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    volumes:
      - ../dev_out:/app/dev_out:ro
    stdin_open: true
    tty: true

secrets:
  sidefx_credentials:
    file: ./sidefx_credentials.env

volumes:
  pip-cache:
  apt-cache:
  apt-lib:
